-- Table: users
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL);

-- Table: status
DROP TABLE IF EXISTS status;
CREATE TABLE IF NOT EXISTS status(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) UNIQUE NOT NULL);

-- Table: tasks
DROP TABLE IF EXISTS tasks;
CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    status_id  INTEGER REFERENCES status(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    user_id  INTEGER REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE);